const goals: Goal[] = [
  {
    id: "1234",
    category: "finance",
    completed: false,
    completionType: "normal",
    durationType: "day",
    finalDate: "121212",
    goalPortions: [],
    initialDate: "121212",
    itGoalPortion: 0,
    name: "save 12$",
    portions: 12,
    repetionsCompleted: null,
    timeCompleted: null,
    timesToDo: 12,
  },
  {
    id: "1235",
    category: "culture",
    completed: false,
    completionType: "normal",
    durationType: "day",
    finalDate: "121212",
    goalPortions: [],
    initialDate: "121212",
    itGoalPortion: 0,
    name: "read book",
    portions: 12,
    repetionsCompleted: null,
    timeCompleted: null,
    timesToDo: 12,
  },
  {
    id: "1236",
    category: "sports",
    completed: false,
    completionType: "normal",
    durationType: "day",
    finalDate: "121212",
    goalPortions: [],
    initialDate: "121212",
    itGoalPortion: 0,
    name: "run 1 mile",
    portions: 12,
    repetionsCompleted: null,
    timeCompleted: null,
    timesToDo: 12,
  },
];

export default goals;
